"""merge user credentials into users

Revision ID: 1f2e922e3f0c
Revises: 50c399f2985d
Create Date: 2026-09-15 17:07:44.355445

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f2e922e3f0c"
down_revision: str | Sequence[str] | None = "50c399f2985d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_credentials")
    op.add_column("users", sa.Column("idp_subject", sa.String(), nullable=False))
    op.add_column("users", sa.Column("idp_source", sa.String(), nullable=False))
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["idp_subject", "idp_source"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_username_key"), "users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "idp_source")
    op.drop_column("users", "idp_subject")
    op.create_table(
        "user_credentials",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("idp_subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("idp_source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_credentials_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_credentials_pkey")),
        sa.UniqueConstraint(
            "idp_subject",
            "idp_source",
            name=op.f("user_credentials_idp_subject_idp_source_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "uuid",
            name=op.f("user_credentials_uuid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
