"""add owner to projects

Revision ID: 50c399f2985d
Revises: 2298e6b8b01c
Create Date: 2026-09-08 15:00:49.861200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50c399f2985d"
down_revision: str | Sequence[str] | None = "2298e6b8b01c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "projects", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "owner_id")
    # ### end Alembic commands ###
