name: Runner test

on:
  pull_request:

permissions:
  contents: read

jobs:
  runner:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runner
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: uv run pytest
